export const COFFEES = [
  {
    id: 'espresso',
    name: 'Espresso',
    emoji: '☕',
    brewTime: 3000,
    strength: 5,
    description: 'Kurz & intensiv',
    cupColor: '#3d1f0a',
    foamColor: null,
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    emoji: '🫖',
    brewTime: 5000,
    strength: 3,
    description: 'Mit Milchschaum',
    cupColor: '#8b5e3c',
    foamColor: '#f5efe8',
  },
  {
    id: 'latte',
    name: 'Latte',
    emoji: '🥛',
    brewTime: 6000,
    strength: 2,
    description: 'Mild & cremig',
    cupColor: '#c49a6c',
    foamColor: '#fdf6ee',
  },
  {
    id: 'americano',
    name: 'Americano',
    emoji: '🫗',
    brewTime: 4000,
    strength: 4,
    description: 'Verlängerter Espresso',
    cupColor: '#5c3317',
    foamColor: null,
  },
  {
    id: 'macchiato',
    name: 'Macchiato',
    emoji: '🍮',
    brewTime: 4000,
    strength: 4,
    description: 'Mit einem Hauch Milch',
    cupColor: '#7b4a1e',
    foamColor: '#f0e0cc',
  },
]
